### ISSUE TITLE
Segmentation fault following symmetry breaking optimization

### ISSUE THREAD

**Issue by smunaut** [RTimothyEdwards/netgen#5]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f9ff3e79f51 in ResolveAutomorphisms () at netcmp.c:5886
5886	          while (E1->graph != Circuit1->file) E1 = E1->next;
(gdb) bt
#0  0x00007f9ff3e79f51 in ResolveAutomorphisms () at netcmp.c:5886
#1  0x00007f9ff3ea5edc in _netcmp_run (clientData=0x0, interp=0x563dfc5a39c0, objc=2, objv=0x563dfc5b1828) at tclnetgen.c:2436
#2  0x00007f9ff4a3f777 in TclNRRunCallbacks () from /lib/x86_64-linux-gnu/libtcl8.6.so
#3  0x00007f9ff4a40b6f in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
#4  0x00007f9ff4af9bb8 in Tcl_FSEvalFileEx () from /lib/x86_64-linux-gnu/libtcl8.6.so
#5  0x00007f9ff4af8517 in Tcl_EvalFile () from /lib/x86_64-linux-gnu/libtcl8.6.so
#6  0x00007f9ff4b0172e in Tcl_SourceRCFile () from /lib/x86_64-linux-gnu/libtcl8.6.so
#7  0x00007f9ff4b01c7d in Tcl_MainEx () from /lib/x86_64-linux-gnu/libtcl8.6.so
#8  0x0000563dfbff4264 in main (argc=9, argv=0x7fffce974a68) at netgenexec.c:82
(gdb) print E1
$1 = (struct Element *) 0x0
(gdb) print Circuit1
$2 = (struct nlist *) 0x563dfc73b6d0
(gdb) 
```

Previous run with 251622c8bc3239adc099faaea498630fa6a9ef2a on the same input finished successfully just took a _long_ time ( ~21.5 h )

**Comment by smunaut** [comment]
Probably not applicable any more ...
